# this manifest is used to deploy an horizontal pod autoscaler which scales couchDB deployment according to couchdb_httpd_database_reads_per_second metric

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: htcondor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wn-pod
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object 
    object:
      metric:
        name: condor_slot_activity_busy
      describedObject:
        apiVersion: batch/v1
        kind: Job
        name: htcondor-pod
      target:
        type: Value
        value: 0.75
