condorHost: 212.189.205.252
ccbHost: 212.189.205.252
proxyCacheHost: 172.30.89.215
ttsCache:
    image: dodasts/tts-cache
    tag: v0.1.3-k8s-12
    iamToken: ...
    iamClientId: ...
htcSchedd:
    image: dodasts/htcondor
    tag: v0.1.0-k8s-schedd-3
    networkInterface: 212.189.205.26
    persistence:
        storageClass: local-path
htcMaster:
    image:  dodasts/htcondor
    tag: v0.1.0-k8s-schedd-3
    networkInterface: 212.189.205.252
htcWn:
    image:  dodasts/htcondor
    tag: v0.1.0-k8s-schedd-3
nfs:
    enabled: false
cvmfs:
    enabled: false
