rules:
  - seriesQuery: 'condor_slot_activity_busy'        
    resources:
      template: "<<.Resource>>"
    name:
      matches: "^(.*)"
      as: "${1}"
    metricsQuery: 'avg(<<.Series>>) by (job)' 
